[versions]
android-targetSdk = "35"
android-compileSdk = "35"
android-minSdk = "28"

agp = "8.13.2"
android-driver = "2.0.1"
androidx-compose = "1.6.4"
androidx-activity-compose = "1.10.1"
core = "1.16.0"
kotlin-stdlib = "2.3.0"
kotlinx-collections-immutable-jvm = "0.3.7"
kotlinx-coroutines = "1.8.0"
kotlin = "2.3.0"
kotlinx-datetime = "0.6.0-RC.2"
kotlinx-serialization-json = "1.6.3"
lifecycle-viewmodel = "2.8.7"
metro = "0.9.1"
slack-circuit = "0.19.1"
square-okhttp = "4.12.0"
turbine = "1.1.0"
gmazzo-buildconfig = "5.5.1"
compose = "1.8.0"
kotlin-ksp = "2.3.3"
compose-plugin = "1.9.3"
square-sort-dependencies = "0.6"
dependency-analysis = "3.5.1"
cashapp-sqldelight = "2.0.1"

[libraries]
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "android-driver" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity-compose" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "slack-circuit" }
circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "slack-circuit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-collections-immutable-jvm = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm", version.ref = "kotlinx-collections-immutable-jvm" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm", version.ref = "kotlinx-datetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okhttp" }
square-okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "square-okhttp" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
cashapp-sqldelight-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "cashapp-sqldelight" }
cashapp-sqldelight-coroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "cashapp-sqldelight" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gmazzo-buildconfig" }
square-sort-dependencies = { id = "com.squareup.sort-dependencies", version.ref = "square-sort-dependencies" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
cashapp-sqldelight = { id = "app.cash.sqldelight", version.ref = "cashapp-sqldelight" }